### ISSUE TITLE
Sketch out performance & scalability documentation/presentation

### ISSUE THREAD

**Issue by MeBrei** [oscoin/osrank-rs#35]
As part of an OKR we want to document and present the assessment of the performance and scalability of the algorithm. This should be extrapolated from benchmarking and profiling data.  

Ideas so far are:

- measure osrank calculation for the first block, ie 1000 nodes
- plot the duration of the osrank calculation for increasing number of nodes and mark the tipping point, ie when does it surpass the allotted time
- if possible do the same calculations for the seed set & incremental approach
- discuss how this compares to the expected runtime and which issues still have to be resolved or could slow down performance

**Comment by MeBrei** [comment]
### WIP outline of a presentation

1. Explain (not in depth but to be able to follow the estimations)
    - naive implementation (random walks)
    - seed set
    - incremental
    - seed set + incremental
2. Establish set boundaries
    - 1000-3000 nodes at genesis
    - 30 seconds threshold
3. Show and evaluate some graphs
   - Graphs: 
      - increasing node count
      - increasing R
      - maybe random_walks, rank_network separately
   - Explanations:
      - upper bound for seed set = times 2
      - means also that we might have to bound the number of changes we allow until osrank is recomputed ?
      - random walk depends on number of starting nodes, damping factor (?), R -> can we give a current limit on random walks we can do in 30s
      - roughly linear: 1000 walks = 4.8 ms (30 s / 5 ms = 6000 -> 6.000.000 walks)
4. missing parts/difficulties of the algo/things that might slow it down
    - graph api
    - how do seed set and inc play together
    - unknowns from the data science side
        - hyper-params & factors (damping factor affects performance)
        - number of iteration to have accurate results
    - benchmarking does not include creating the graph and its weights, not only osrank has to run -> 30 s might be to much 
5. improvement possibilities
    - better Rust code 
        - parallelisation
    - incremental algorithm
    - handling of floats?
    - not writing directly to the graph

**Comment by MeBrei** [comment]
I tweaked a plot from the benchmark of `iter 1` and `10` to include `iter 100` as well as some extra information. @adinapoli-mndc let me know if I should add or change anything.
![osrank_performance](https://user-images.githubusercontent.com/16262137/64868384-868a3900-d63f-11e9-80fd-aa3e7762b4fb.jpg)

With the following python script, the approximate polynomial equation of `iter 1` can be calculated.

```
import numpy as np
  
x = np.array ([1000, 2500, 5000, 7500, 10000, 15000, 17779, 19012, 20957])
y = np.array ([0.015943, 0.089199, 0.35654, 0.99268, 1.8604, 7.5682, 7.6328, 8.6775, 10.571])
z2 = np.polyfit(x, y, 2)
poly2 = np.poly1d(z2)
print(poly2)
```

With this we can do some approximations for example on when it hits 30 seconds or on how long it would take to currently calculate the osrank for the hole network presented on github.
Which turns out is about 2.5 years taking numbers from a [github survey](https://octoverse.github.com) (31m developers + 96m repositories). 😄

**Comment by adinapoli-mndc** [comment]
> I tweaked a plot from the benchmark of iter 1 and 10 to include iter 100 as well as some extra information. @adinapoli-mndc let me know if I should add or change anything.

This is amazing @MeBrei , well done! 🎉 🥇 

> Which turns out is about 2.5 years taking numbers from a github survey (31m developers + 96m repositories).

Sounds about right 😂

**Comment by adinapoli-mndc** [comment]
This is now done, as the summer quarter wrapped up.
