### ISSUE TITLE
Require the Graph to be "normalised" before calling `GraphAlgorithm::execute`

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/osrank-rs#66]
This is mostly an API design brainstorming exercise that occurred to me while I was working on #51. At some point during my visualisation task, I was unsure whether or not the ranking I was seeing was wrong due to some labeling (which turned out be the culprit) or simply due to the fact the input `Graph` wasn't "normalised". By "normalised" here I mean a graph where we have only one outgoing edge for each `(Node1,Node2)` pair and any parallel edge is collapsed and the overall weight normalised. 

The algorithm clearly needs to be able to work with a graph of such shape, but our very abstract `Graph` trait doesn't constraint us in this sense. Therefore, I am musing if we should have some trait like:

``` rust
pub trait Normalised: Graph {
  fn normalise(&mut self);
}
```

And now have `GraphAlgorithm` being defined such as (*NOTE*, this skips for conveniency the new `GraphAnnotator` abstraction):

``` rust
pub trait GraphAlgorithm<G>
where
    G: GraphDataWriter + Normalised,
{
    /// Mutable context of the execution.
    /// Can be used as a stateful cache.
    /// The first time `execute` is called,
    /// `Context::default()` is passed in.
    type Context: Default;

    /// The output of the execution.
    type Output;

    /// An execution error.
    type Error;

    /// A seed suitable for an RNG.
    type RngSeed;

    /// Execute an algorithm over a context and graph.
    /// Changes to the context will be persisted across
    /// executions of the algorithm.
    fn execute(
        &self,
        context: &mut Self::Context,
        graph: &G,
        annotator: ...
        seed: Self::RngSeed,
    ) -> Result<Self::Output, Self::Error>;
}
```

Having said that, I am wondering if this would be too heavy, because it would require to expose the `Normalised` trait into the `graph-api` and force implementors to provide _us_ a production-like `Normalised` implementation. But a "real world" graph might not be normalise-able, or perhaps this is something that `osrank` should take an active responsibility for.

If the last sentence makes sense, then the proper way to do this is to add the constraint not to the trait, but on the concrete algorithm itself. In other terms, it's now _our_ responsibility to change the type signature of `osrank_naive` to be:

```
pub fn osrank_naive<G>(
    seed_set: Option<&SeedSet<Id<G::Node>>>,
    network: &mut G,
    ledger_view: &impl LedgerView,
    rng: &mut (impl Rng + SeedableRng),
    set_osrank: &dyn Fn(&mut G::Node, Osrank) -> (),
) -> Result<(), OsrankError>
where
    G: GraphExtras + Clone + Normalised,
    Id<G::Node>: Clone + Eq + Hash,
    <G as Graph>::Weight:
        Default + Clone + PartialOrd + for<'x> AddAssign<&'x G::Weight> + SampleUniform,
{
...
```

In a way that this will bubble right to the call site of this function (which is the concrete implementation for `GraphAlgorithm`). This doesn't leak this trait in the `GraphAlgoritm` _definition_ but surely in the _implementation_, which means the `protocol` folks will still need to implement `normalise` on their end, which doesn't sound right either (this is because, if I remember correctly, you cannot really have orphan instances for traits like in haskell, so even if we wanted, we couldn't define `impl Normalised for RealWorldGraph`.

@MeBrei What do you think? Do you see where I am coming from? I suspect we might need to keep this in the back of our minds for a while before finding a design that fits.

**Comment by cloudhead** [comment]
Kind of weird that a normalised graph would have a `normalise` function, no?

How about `impl Into<NormalizedGraph> for Graph` and then `let normalized: NormalizedGraph = g.into()`

**Comment by adinapoli-mndc** [comment]
Yeah, I agree, that was a weird interface -- using the `Into` pattern feels definitely more idiomatic here. At this point them our `NormalisedGraph` could be decomposed into a simple newtype wrapper like:

```
pub struct Normalised<G> {
  normalised: G
}
```

Then the programmer would be forced to *think* about the deliberate choice of normalising a graph. For testing purposes this could be implemented as the identity function, but at least now we have a layer of coating between running the algorithm and providing the graph.

**Comment by cloudhead** [comment]
Yeah exactly. You can then implement `Deref` so that the methods of `G` are accessible from `Normalized<G>`
